spring:
  application:
    name: spring-boot-template
  profiles:
    active: dev
  servlet:
    multipart:
      enabled: true
      max-file-size: 1024MB
      max-request-size: 1024MB
  cloud:
    sentinel:
      enabled: true
      transport:
        dashboard: 127.0.0.1:8080
      datasource:
        ds1:
          # 对应 DataSourcePropertiesConfiguration 类
          nacos:
            server-addr: 192.168.239.240:8848 # Nacos 服务器地址
            namespace: # Nacos 命名空间
            group-id: DEFAULT_GROUP # Nacos 分组
            data-id: ${spring.application.name}-flow-rule # Nacos 配置集编号
            data-type: json # 数据格式
            rule-type: FLOW # 规则类型

server:
  servlet:
    encoding:
      force: true #解决静态资源乱码问题

mybatis-plus:
  type-aliases-package: com.kai.entity
  mapper-locations: classpath:/xml/*Mapper.xml
  global-config:
    db-config:
      logic-delete-field: deleted  #全局逻辑删除字段值，3.3.0开始支持
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

auth:
  add-path-patterns:
    - "/**"
  exclude-path-patterns:
    - "/login/**"
    - "/permission/**"
    - "/v3/api-docs/**"
    - "/swagger-ui/**"
    - "/swagger-resources/**"