spring:
  application:
    name: spring-boot-template
  profiles:
    active: dev
    include: core

mybatis-plus:
  type-aliases-package: com.kai.entity
  mapper-locations: classpath:/xml/*Mapper.xml
  global-config:
    db-config:
      logic-delete-field: deleted  #全局逻辑删除字段值，3.3.0开始支持
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

auth:
  add-path-patterns:
    - "/**"
  exclude-path-patterns:
    - "/login/**"
    - "/permission/**"
    - "/v3/api-docs/**"
    - "/swagger-ui/**"
    - "/swagger-resources/**"

web-log:
  pointcut: execution(* com.kai.controller..*.*(..))

ali-yun:
  sms:
    access-key-id: 123456
    access-key-secret: 123456
    ali-yun-sms-channel-map:
      channel-001:
        template-name: name
        sign-name: name
        template-code: code
        template-content: content