server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://1.116.114.206:3306/test?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    username: kai
    password: qwertyuiop
  redis:
    host: 127.0.0.1
    port: 6379
#    password: redis+abc
    database: 0

logback:
  filePath: /application/spring-boot-template/logs/  # 日志文件存储目录

upload:
  path: /application/spring-boot-template/upload/  # 上传文件存储目录
  url: http://localhost:8080/ # 文件读取地址