spring:
  application:
    name: spring-boot-template
  profiles:
    active: dev
  servlet:
    multipart:
      enabled: true
      max-file-size: 1024MB
      max-request-size: 1024MB
  cloud:
    sentinel:
      enabled: true

mybatis-plus:
  type-aliases-package: com.kai.entity
  mapper-locations: classpath:/xml/*Mapper.xml
  global-config:
    db-config:
      logic-delete-field: deleted  #全局逻辑删除字段值，3.3.0开始支持
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

auth:
  add-path-patterns:
    - "/adminApi/**"
    - "/userApi/**"
  exclude-path-patterns:
    - "/adminApi/login/**"
    - "/adminApi/permission/**"
    - "/userApi/login/**"