server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/spring_boot_template?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0

logging:
  level:
    com:
      kai: DEBUG

logback:
  path: /application/spring-boot-template/logs/  # 日志文件存储目录

upload:
  path: /application/spring-boot-template/upload/  # 上传文件存储目录
  url: 192.168.11.62:${server.port}/upload/ # 文件读取地址